# puerto donde va a correr el microservicio
server.port=8002

spring.application.name=game-service

# Base de datos con memoria H2 asi que no se necesita instalar nada de nada
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# con est se crean las tablas automáticamente al iniciar
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true

# esto permite ver la base de datos en el navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true